### ISSUE TITLE
wazzup man

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#16]
yo man, what are the news?

~~i haven't been using surfer for somedays~~
~~i'll try again, i hope the problem with the videos is gone now~~
yeah videos and gifs are still broken

i tried to use sway but got so many problems with the configuration that i just gave up

and about learning C
i'm not going good, i don't understand
i think i am starting wrong
how should i start learning C?

**Comment by nihilowy** [comment]
I added file for  customizing css per site  although i dont use it but just for fun.. but finally disabled it ,  due to bookmarks add problems but now seems ok.
videos are workin , you must have spoil sth . 
sway - is worth try but there are some issue ( but it not so unstable like webkit in my opinions) . 
about c - there are many libs libc, glib , gtk, webkit ,gstream . No one these days write in pure c .
 even these libs  are based on some lower level .. Beside why to do this? its for freaks  or proffesionals .

**Comment by ghost** [comment]
i'm just angry as hell now
~~i don't know what i should do to fix the videos~~
~~ok now the videos are working again~~
~~i remove everything with webkit and gstreamer~~
~~and installed the minimum libs necessary to run and kept installing and installing more libs until the videos worked~~
~~but i don't know if they will keep working well for long because the same happened before~~

its broken
just broken

**Comment by nihilowy** [comment]
hehe
well I also tried minimal set gstreamer. I noticed that gst-plugins-bad makes problem on some sites 
(but gst-plugins-bad-libs are required).
so my set is
pacman -Q | grep gst
gst-libav 1.16.2-2
gst-plugins-bad-libs 1.16.2-13
gst-plugins-base 1.16.2-2
gst-plugins-base-libs 1.16.2-2
gst-plugins-good 1.16.2-3
gstreamer 1.16.2-2

But chill out . You can use epiphany or beter firefox :)

**Comment by ghost** [comment]
i really want a small browser like surfer
i use firefox as my main browser and surfer as my secondary browser
to make fast searchs, test html files, and some broken sites on firefox because umatrix or adblock do work on surfer
to me its essential to have a small browser like that
its small and fast

**Comment by ghost** [comment]
you think its possible to compile surfer in a static binary?
with all dependencies in one file

**Comment by nihilowy** [comment]
maybe. its is bad idea. I added my binary maybe it will help yo somehow. It is compilled by gcc

**Comment by ghost** [comment]
its working now
i removed "gst-plugins-bad"
i hope it keeps working
