### ISSUE TITLE
Add license, pkgbuild revision

### ISSUE THREAD

**Issue by FabioLolix** [nihilowy/surfer#30]
Hello, your github repository lack a license, in your AUR pkgbuild is indicated GPL(2), please add it here

Your AUR pkgbuild lacks a pkgver() function and release 4 don't exist, 

https://wiki.archlinux.org/title/VCS_package_guidelines#The_pkgver()_function

Attached there both a revisioned pkgbuild and patch

[0001-revision.patch.txt](https://github.com/nihilowy/surfer/files/7698792/0001-revision.patch.txt)
[PKGBUILD.txt](https://github.com/nihilowy/surfer/files/7698793/PKGBUILD.txt)

**Comment by nihilowy** [comment]
hi thx. 
I added license. pkgver is obsolete , name of aur repo is with -git (surfer-git)  . Some day I will remove it.

**Comment by FabioLolix** [comment]
> name of aur repo is with -git (surfer-git)

Yes, as is it in the pkgbuild I attached

> pkgver is obsolete

The current pkgver= is incorrect, and a pkgver() function is needed

**Comment by nihilowy** [comment]
OK I patched. Thanks . (first  I always have to generate new ssh-key to change it on aur site, because I dont keep it on disk).
By the way,  compiling it from aur is causing crashes after opening new window. Its  because the use these make flags  like fortify etc. 
I dont know how to repair these, yet compiling webkit with symbols for debug , is not for my cpu .
