### ISSUE TITLE
Downloads?

### ISSUE THREAD

**Issue by azer** [nihilowy/surfer#4]
Hey, 

I love Suckless Surf, so found this work. Thanks a lot for creating it! 

I was wondering - if it currently implements support for downloading attachments ? 

I went through the code, saw lots of disabled lines. Just wanted to ask here.

Cheers
Azer

**Comment by nihilowy** [comment]
Hi 
I worked on it - it is not so simple , so I decided to abandon it  for  now because usually it works ( sometimes to download I click with ctrl ) .

Unfortunatlly - webkit2gtk - (web core of webkit based browsers) recent versions ( from 2.4.1 forward )  make freezes on many sites .So until it will not improves I dont see futere bright for theses small browsers. NOW I still use webkit2gtk 2.4.0  (downgreaded on linux Arch)

greetings

**Comment by azer** [comment]
thanks for the answer!

**Comment by nihilowy** [comment]
Hi 
I added some code  - will see how it goes

**Comment by nihilowy** [comment]
button on open bar :)
